name: flutter_application
description: Pokemon Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    flutter_barcode_scanner: ^2.0.0
flutter:
  assets:
    - assets/pokemon-go-wallpaper.jpg

